module.exports = {
    beforeEach: browser => {
        browser.url('https://alpha.yoodlize.com/')
    },
    after: browser => {
        browser.end()
    },
    'yoodlizeShit': browser => {
        browser
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[1]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[2]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[3]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[4]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[5]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[6]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[7]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[8]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[9]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[10]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[11]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[12]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[13]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[14]') 
        .back()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[15]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[1]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[2]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[3]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[4]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[5]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[6]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[7]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[8]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[9]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[10]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[11]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[12]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[13]') 
        .back()
        .click('(//div[@class="h-125 p-s f f-rows f-start-center bg-offWhite"])[14]') 
        .back()
        .setValue('//input',['Dog', browser.Keys.ENTER])
      
    }
}